import streamlit as st
import os
import markdown
from dotenv import load_dotenv
from google import genai
from docx import Document

# 1. Load Keys
load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")

# --- BRANDING CONFIGURATION ---
st.set_page_config(
    page_title="Career Pivot AI",
    page_icon="logo.png",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CUSTOM LOGO (Sidebar) ---
st.logo(
    "logo.png",
    link="https://your-carrd-website.carrd.co", 
    icon_image="logo.png"
)

# --- CLEANUP CSS ---
hide_streamlit_style = """
            <style>
            #MainMenu {visibility: hidden;}
            footer {visibility: hidden;}
            header {visibility: hidden;}
            </style>
            """
st.markdown(hide_streamlit_style, unsafe_allow_html=True)

# --- PASSWORD PROTECTION ---
def check_password():
    """Returns `True` if the user had the correct password."""
    def password_entered():
        if st.session_state["password"] == "PIVOT2025":
            st.session_state["password_correct"] = True
            del st.session_state["password"]
        else:
            st.session_state["password_correct"] = False

    if "password_correct" not in st.session_state:
        st.text_input(
            "🔑 Enter Access Code (From your Gumroad Receipt):", 
            type="password", 
            on_change=password_entered, 
            key="password"
        )
        return False
    elif not st.session_state["password_correct"]:
        st.text_input(
            "🔑 Enter Access Code:", 
            type="password", 
            on_change=password_entered, 
            key="password"
        )
        st.error("😕 Access code incorrect")
        return False
    else:
        return True

if check_password():
    # --- HELPER FUNCTIONS ---
    def clean_text(text):
        text = text.replace("```markdown", "").replace("```", "")
        return text.strip()

    def create_html_report(text_content):
        html_body = markdown.markdown(text_content, extensions=['tables'])
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Career Pivot Strategy</title>
            <style>
                body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; background-color: #f9f9f9; }}
                .container {{ background-color: #ffffff; padding: 50px; border-radius: 8px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }}
                h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
                h2 {{ color: #2980b9; margin-top: 30px; }}
                table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
                th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
                th {{ background-color: #3498db; color: white; }}
                tr:nth-child(even) {{ background-color: #f2f2f2; }}
                .footer {{ margin-top: 50px; font-size: 0.8em; text-align: center; color: #7f8c8d; border-top: 1px solid #eee; padding-top: 20px; }}
            </style>
        </head>
        <body>
            <div class="container">
                {html_body}
                <div class="footer">Generated by Career Pivot AI &copy; 2025</div>
            </div>
        </body>
        </html>
        """

    def create_word_doc(text_content):
        doc = Document()
        doc.add_heading('Rewritten Resume (Draft)', 0)
        for line in text_content.split('\n'):
            if line.startswith('# '):
                doc.add_heading(line.replace('# ', ''), level=1)
            elif line.startswith('## '):
                doc.add_heading(line.replace('## ', ''), level=2)
            elif line.startswith('* '):
                try:
                    doc.add_paragraph(line.replace('* ', ''), style='List Bullet')
                except:
                    doc.add_paragraph(line)
            else:
                doc.add_paragraph(line)
        doc_filename = "Rewritten_Resume.docx"
        doc.save(doc_filename)
        return doc_filename

    # --- MAIN UI ---
    
    # Create 2 columns
    col1, col2 = st.columns([2, 5]) 
    
    with col1:
        st.image("logo.png", width=250) 

    with col2:
        st.title("Career Pivot AI")
    
    st.markdown("### ✨ Premium Access Unlocked")

    uploaded_file = st.file_uploader("Upload Client Resume (PDF)", type=["pdf"])

    if uploaded_file is not None:
        tab1, tab2 = st.tabs(["📊 1. Strategy Report", "📝 2. Resume Rewrite"])
        client = genai.Client(api_key=api_key)

        with tab1:
            st.header("Step 1: The Strategy")
            if st.button("Generate Strategy Report", key="btn_strategy"):
                with st.spinner("Auditing Resume..."):
                    try:
                        temp_filename = "temp_resume.pdf"
                        with open(temp_filename, "wb") as f:
                            f.write(uploaded_file.getbuffer())
                        file_ref = client.files.upload(file=temp_filename)
                        
                        prompt_strategy = """
                        Role: Senior Tech Recruiter.
                        Task: Create a $49 Career Pivot Strategy Report.
                        Output: Markdown with Tables. DO NOT wrap output in code blocks.
                        Sections:
                        1. 🛑 ATS Audit (3 Red Flags)
                        2. 🔑 Skills Translation Table (Old vs New phrasing)
                        3. ✍️ Summary Rewrite
                        4. 🛠️ Cert Roadmap
                        5. 💼 LinkedIn Optimization
                        """
                        response = client.models.generate_content(model="gemini-2.0-flash", contents=[file_ref, prompt_strategy])
                        clean_response = clean_text(response.text)
                        
                        st.success("Strategy Ready!")
                        html_report = create_html_report(clean_response)
                        st.download_button("📥 Download HTML Report", html_report, "Strategy_Report.html", "text/html")
                        st.markdown("---")
                        st.markdown(clean_response)
                        os.remove(temp_filename)
                    except Exception as e:
                        st.error(f"Error: {e}")

        with tab2:
            st.header("Step 2: The Rewrite")
            if st.button("Draft New Resume (.docx)", key="btn_rewrite"):
                with st.spinner("Rewriting Resume..."):
                    try:
                        temp_filename = "temp_resume.pdf"
                        with open(temp_filename, "wb") as f:
                            f.write(uploaded_file.getbuffer())
                        file_ref = client.files.upload(file=temp_filename)
                        
                        prompt_rewrite = """
                        Role: Professional Resume Writer.
                        Task: Rewrite resume for Entry-Level IT Support.
                        Output: Clean Markdown. DO NOT wrap output in code blocks.
                        Structure:
                        # [Client Name]
                        ## Professional Summary
                        ## Technical Skills
                        ## Professional Experience
                        ## Education
                        """
                        response = client.models.generate_content(model="gemini-2.0-flash", contents=[file_ref, prompt_rewrite])
                        clean_response = clean_text(response.text)
                        
                        st.success("Resume Drafted!")
                        docx_file = create_word_doc(clean_response)
                        with open(docx_file, "rb") as f:
                            st.download_button("📥 Download Word Doc", f, "Rewritten_Resume.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
                        st.markdown("### Preview")
                        st.markdown(clean_response)
                        os.remove(temp_filename)
                    except Exception as e:
                        st.error(f"Error: {e}")

    # --- SIDEBAR FEEDBACK MECHANISM (NEW ADDITION) ---
    with st.sidebar:
        st.divider()
        st.markdown("### 🗣️ Beta Feedback")
        st.write("Help Elijah improve this tool!")
        
        feedback_rating = st.slider("How accurate was the advice?", 1, 5, 5)
        feedback_text = st.text_area("Any bugs or weird suggestions?")
        
        if st.button("Submit Feedback"):
            # Saves to a local CSV file
            with open("feedback_log.csv", "a") as f:
                f.write(f"{feedback_rating},{feedback_text}\n")
            st.success("Thank you! Feedback recorded.")